[package]
name = "rs-crypto"
version = "0.1.0"
authors = ["Michael Pyle <mpyle101@gmail.com>"]
edition = "2018"

[dependencies]
aes-gcm = "0.8.0"
hmac = "0.10.1"
openssl = "0.10.33"
rand = "0.8.3"
rust-argon2 = "0.8.3"
sha2 = "0.9.3"
zeroize = "1.2.0"

[profile.dev]
split-debuginfo = "unpacked"
